const userTypes = {
    START_REGISTER: 'START_REGISTER',
    SUCCESS_REGISTER: 'SUCCESS_REGISTER',
    FAIL_REGISTER: 'FAIL_REGISTER',

    START_LOGIN: 'START_LOGIN',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    FAIL_LOGIN:'FAIL_LOGIN',
    SUCCESS_SET_CURRENT_USER: 'SUCCESS_SET_CURRENT_USER',

    SUCCESS_SIGNOUT: 'SUCCESS_SIGNOUT',
    SUCESS_LOGIN_TRUE: 'SUCESS_LOGIN_TRUE',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS'
}

export default userTypes