const categoryTypes = {
    START_CREATE_CATEGORY: 'START_CREATE_CATEGORY',
    SUCCESS_CREATE_CATEGORY: 'SUCESS_CREATE_CATEGORY',
    FAIL_CREATE_CATEGORY: 'FAIL_CREATE_CATEGORY'
    
}

export default categoryTypes