const blogTypes = {
    START_CREATE_BLOG: 'START_CREATE_BLOG',
    SUCCESS_CREATE_BLOG: 'SUCESS_CREATE_BLOG',
    FAIL_CREATE_BLOG: 'FAIL_CREATE_BLOG',
    BLOGS_TOTAL: 'BLOGS_TOTAL',
    INCREMENT_BLOGS_TOTAL: 'INCREMENT_BLOGS_TOTAL'
    
}

export default blogTypes